window.YR_PROJECTS = [
  {
    id: "2026-300",
    projectNumber: "2026.300",
    title: "Interior Remodel — Bedroom & Bathroom Reconfiguration",
    city: "Lakewood, CA",
    publicLocation: "Lakewood, CA",
    lat: 33.8536,
    lng: -118.1339,
    status: "Active",
    phases: ["Design & Permitting", "Construction"],
    projectType: "Single-Family Residence",
    scope: ["Remodel"],
    notes: "Adding a new bedroom and new bathroom within existing walls.",
    image: null,
    page: null,
    featured: false,
    illustrative: false
  },
  {
    id: "2026-301",
    projectNumber: "2026.301",
    title: "Residential Interior Remodel",
    city: "Long Beach, CA",
    publicLocation: "Long Beach, CA",
    lat: 33.8248,
    lng: -118.1745,
    status: "Active",
    phases: ["Design & Permitting", "Construction"],
    projectType: "Single-Family Residence",
    scope: ["Remodel"],
    notes: "Residential remodel.",
    image: null,
    page: null,
    featured: false,
    illustrative: false
  },
  {
    id: "2026-302",
    projectNumber: "2026.302",
    title: "Residential Remodel & Reconstruction",
    city: "Sierra Madre, CA",
    publicLocation: "Sierra Madre, CA",
    lat: 34.1617,
    lng: -118.0528,
    status: "Active",
    phases: ["Design & Permitting", "Construction"],
    projectType: "Single-Family Residence",
    scope: ["Remodel", "Reconstruction"],
    notes: "Residential remodel and reconstruction.",
    image: null,
    page: null,
    featured: false,
    illustrative: false
  },
  {
    id: "2026-304",
    projectNumber: "2026.304",
    title: "Interior Remodel & Conversion",
    city: "La Habra Heights, CA",
    publicLocation: "La Habra Heights, CA",
    lat: 33.9608,
    lng: -117.9506,
    status: "Active",
    phases: ["Design & Permitting", "Construction"],
    projectType: "Single-Family Residence",
    scope: ["Remodel", "Conversion"],
    notes: "Adding two new bathrooms and one new bedroom within existing walls.",
    image: null,
    page: null,
    featured: false,
    illustrative: false
  },
  {
    id: "2026-306",
    projectNumber: "2026.306",
    title: "750 SF Residential Addition & Remodel",
    city: "Bellflower, CA",
    publicLocation: "Bellflower, CA",
    lat: 33.8817,
    lng: -118.1170,
    status: "Active",
    phases: ["Design & Permitting", "Development", "Construction"],
    projectType: "Single-Family Residence",
    scope: ["Addition", "Remodel"],
    notes: "Approximately 750 square foot addition.",
    image: null,
    page: null,
    featured: false,
    illustrative: false
  },
  {
    id: "2026-311",
    projectNumber: "2026.311",
    title: "Kitchen & Bathroom Remodel",
    city: "Orange, CA",
    publicLocation: "Orange, CA",
    lat: 33.7879,
    lng: -117.8531,
    status: "Active",
    phases: ["Design & Permitting", "Construction"],
    projectType: "Single-Family Residence",
    scope: ["Remodel"],
    notes: "Like-for-like kitchen and bathroom remodels.",
    image: null,
    page: null,
    featured: false,
    illustrative: false
  },
  {
    id: "2026-312",
    projectNumber: "2026.312",
    title: "Interior Remodel & Garage Conversion",
    city: "Long Beach, CA",
    publicLocation: "Long Beach, CA",
    lat: 33.7595,
    lng: -118.1460,
    status: "Active",
    phases: ["Design & Permitting", "Construction"],
    projectType: "Single-Family Residence",
    scope: ["Remodel", "Conversion"],
    notes: "Interior remodel including kitchen and bathroom work, a new bathroom within existing walls, interior reconfiguration, and conversion of the existing garage to a bedroom.",
    image: null,
    page: null,
    featured: false,
    illustrative: false
  }
];
